matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    cache:
      directories:
      - "$HOME/.npm"
      - ".git"
    env:
    - builder=travis
language: node_js
node_js:
- 8
addons:
  apt:
    packages:
    - curl
    - socat
    - time
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    npm install -g gatsby-cli gh-pages;
  fi
script:
- npm i
- /bin/bash -l -c "/usr/bin/time -v make -e ci"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: false
  local-dir: public
  target-branch: master
  fqdn: stawkyard.com
  verbose: true
  on:
    branch: gatsby
