#!/usr/bin/env sh
: ${BLENDVR_DIR:=$HOME/.blendvr}
: ${BLENDVR_BIN:=$BLENDVR_DIR/bin}
: ${VERBOSITY:=0}
TARGET=$1

set -e
set -u

if type "$TARGET" > /dev/null; then
  if [ $VERBOSITY -gt '0' ]; then
    echo "$TARGET found in path"
  fi
  if [ ! -e $BLENDVR_BIN/$TARGET ]; then
    ln -s $(which $TARGET) $BLENDVR_BIN/$TARGET
    if [ $VERBOSITY -gt '0' ]; then
      ls -al $BLENDVR_BIN/$TARGET
    fi
  fi
else
  if [ $VERBOSITY -gt '0' ]; then
    echo "$TARGET not found attempting to make..."
  fi
    make -e $BLENDVR_BIN/$TARGET
fi
